### ISSUE TITLE
Darwin binary needs to be signed to run on macOS

### ISSUE THREAD

**Issue by aareet** [hashicorp/terraform-plugin-docs#1]
<img width="1089" alt="Screen Shot 2020-07-15 at 3 39 46 PM" src="https://user-images.githubusercontent.com/33654/87607098-6be67d80-c6b1-11ea-8424-22ee2a9efa92.png">

Tested with the 0.1.0 release binary.

**Comment by detro** [comment]
I believe this is no more the case. Closing.
