### ISSUE TITLE
Support Emitting of DeprecationMessage to Generated Markdown

### ISSUE THREAD

**Issue by jbristowe** [hashicorp/terraform-plugin-docs#10]
If a resource has `DeprecationMessage` field then a [callout](https://www.terraform.io/docs/registry/providers/docs.html#callouts) should be emitted to the generated Markdown.

Example:

![image](https://user-images.githubusercontent.com/71493/100942205-a2c90d00-3546-11eb-8d8f-8afa974ca15a.png)

**Comment by paultyng** [comment]
I agree this would be great to include, unfortunately deprecation messages are not included in the schema exported from Terraform, only a bool indicating its deprecated. Your best bet would be customize the description (or description generator) for a resource, see the [`ResourceDescriptionBuilder`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema#pkg-variables) in the SDK to hook the generated description and append that message.

Scaffolding has an example of how to do similar for defaults: https://github.com/hashicorp/terraform-provider-scaffolding/blob/bec212504f3fc7ad42e5f3a80425cb95872dda28/internal/provider/provider.go#L15-L23

**Comment by paultyng** [comment]
Going to close this since there isn't a way to achieve it in the generator, but happy to include an example on the scaffolding repo and link to it to solve this for folks.
