### ISSUE TITLE
Running v0.7.0 in Actions, with terraform on PATH, gives invalid character 'c' looking for beginning of value

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform-plugin-docs#127]
Only running in GH Actions CI (vs. my also-amd64 machine) and only if `terraform` is already on `$PATH`, v0.7.0 (which began to use it from PATH) errors:

```
using Terraform CLI binary from PATH if available, otherwise downloading latest Terraform CLI binary
running terraform init
getting provider schema
Error executing command: unable to generate website: invalid character 'c' looking for beginning of value
```

(For example: https://github.com/OJFord/terraform-provider-wireguard/runs/5590511618)

I haven't been able to reproduce this outside of Actions, even using `act`, which makes it quite difficult to debug.

I've worked around it by letting it acquire terraform itself instead.

**Comment by bflad** [comment]
Hey @OJFord 👋  Thanks for raising this and sorry you ran into trouble.

If you're using the [`hashicorp/setup-terraform`](https://github.com/hashicorp/setup-terraform) GitHub Action, you'll need to ensure the wrapper is disabled so the `terraform` binary is installed normally.

e.g.

```yaml
- uses: hashicorp/setup-terraform@v1
  with:
    terraform_wrapper: false
```

Can you double check you have that configuration? Thanks.

**Comment by OJFord** [comment]
Ah! That was indeed how I was installing it (without that option).

Might be worth mentioning that in the readme here (assuming it can't be avoided/isn't a bug in the action?) - since that action's description of it doesn't really make clear why/that it could be a problem (just 'can be optionally skipped').

Cheers.
