### ISSUE TITLE
Upgrade github.com/russross/blackfriday to latest stable version

### ISSUE THREAD

**Issue by detro** [hashicorp/terraform-plugin-docs#131]
Unfortunately in 2.x [russross/blackfriday](https://github.com/russross/blackfriday) breaks compatibility, so we had to prevent Dependabot from [just bumping it up](https://github.com/hashicorp/terraform-plugin-docs/pull/104).

This library is the markdown processor used by this project.

Despite this, we want to upgrade it to the latest stable version, but it will require an active implementation change.

**Comment by SBGoods** [comment]
Superseded by: #321
