### ISSUE TITLE
Error executing command: unable to generate website: configuration is invalid

### ISSUE THREAD

**Issue by cloud-j-luna** [hashicorp/terraform-plugin-docs#169]
I get the error `Error executing command: unable to generate website: configuration is invalid` when running `go generate` on my provider.

I have the following structure in the `examples` folder
<img width="361" alt="image" src="https://user-images.githubusercontent.com/7607329/178373897-81927b05-7ad4-4bea-8a47-dcf539a2303a.png">
and the following comment in my `main.go`
```go
//go:generate go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs --provider-name=<my provider hostname/namespace/type>
```

I'm running the command in the root directory of the provider.

Any clues on what can be happening? The logs say some configuration is invalid, I'm not really sure which one.
Thank you.

**Comment by lrstanley** [comment]
Hello @cloud-j-luna, if https://github.com/hashicorp/terraform-plugin-docs/pull/174 is merged, it may help improve the error output for you to troubleshoot this further. I believe another issue could be related to `--provider-name`. For example, if your provider is `domain.com/project/my-provider-here`, what should be passed into `--provider-name` is `my-provider-here`.
