### ISSUE TITLE
Rendered provider name not being picked up

### ISSUE THREAD

**Issue by posriniv** [hashicorp/terraform-plugin-docs#173]
The latest version of tfplugindocs doesn't use the `--rendered-provider-name` parameter while generating the documentation.

**Comment by jacobbednarz** [comment]
can you provide more details on this? we are using the latest version with this flag and it is working as expected.

**Comment by posriniv** [comment]
@jacobbednarz The value I pass in as --provider-name is being used in the place where --rendered-provider-name must be used. Can you please let me know what other information would help you?

**Comment by jacobbednarz** [comment]
if you clone https://github.com/cloudflare/terraform-provider-cloudflare and run `make docs`, it should demonstrate this in use and working. 

if you can provide a similar repro, I can take a look for you.

**Comment by posriniv** [comment]
Our repository is not public yet. However, when I tried it on Cloudflare Terraform provider with a different name, I see that the rendered provider name got updated in the resources docs but it didn't get updated on `index.md`. Is this the expected behavior?

For example, I changed the rendered provider name to `New Cloudflare` and ran `make docs`
Here is the page for `docs/resources/access_application.md`
```
---                                                                                                  
page_title: "cloudflare_access_application Resource - New Cloudflare"                                
subcategory: ""                                                                                      
description: |-                                                                                      
  Provides a Cloudflare Access Application resource. Access                                          
  Applications are used to restrict access to a whole application using an                           
  authorisation gateway managed by Cloudflare. 
.
.
```  
And, here is the page for docs/index.md
```
---                                                                                                  
layout: ""                                                                                           
page_title: "Provider: Cloudflare"                                                                   
description: |-                                                                                      
  The Cloudflare provider provides resources to interact with the Cloudflare API.                    
---  
```

**Comment by jacobbednarz** [comment]
It uses a custom template that doesn't use the variable - https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/templates/index.md.tmpl, so, yes.

**Comment by posriniv** [comment]
@jacobbednarz I see. I didn't create any templates directory and it is not being created when I run `generate` either. Is there a way to automatically generate the templates directory and files? I fail to see it in the docs. Thanks a lot for the help.

**Comment by jacobbednarz** [comment]
you don't have to have a templates directory unless you want to customise it (like using the rendered provider name instead of the default provider name). out of the box, the default index and resource template don't use it so it is a noop.

**Comment by posriniv** [comment]
@jacobbednarz Thank you very much. Closing the issue.
