### ISSUE TITLE
Github dependabot security alert shown while using terraform-plugin-docs v0.13.0 

### ISSUE THREAD

**Issue by prakkarp** [hashicorp/terraform-plugin-docs#183]
Upgrade the dependency github.com/Masterminds/sprig/v3 v3.2.2 which has a dependency on github.com/Masterminds/goutils v1.1.0. 
Here is the advisory highlighting the issue:
https://github.com/advisories/GHSA-xg2h-wx96-xgxr

**Comment by bflad** [comment]
Hi @prakkarp 👋 Thank you for raising this. https://github.com/hashicorp/terraform-plugin-docs/pull/196, which has been merged into the `main` branch now and will be released in v0.14.0, should resolve this dependency update.
