### ISSUE TITLE
Support external provider binaries that are not built by go

### ISSUE THREAD

**Issue by teneko** [hashicorp/terraform-plugin-docs#195]
Hi. I am author [pseudo-dynamic/Terraform.Provider.Scaffolding](https://github.com/pseudo-dynamic/Terraform.Provider.Scaffolding) that is written in C# and uses [PseudoDynamic.Terraform.Toolset](https://github.com/pseudo-dynamic/PseudoDynamic.Terraform.Toolset) as provider framework.

I wanted to ask you kindly, whether you would like to support specifying a path to a custom provider binary, so that I can point to the Terraform provider artifact compiled by `dotnet`.

For reference: This is the repository I would like to generate a Terraform provider plugin documentation for:  [pseudo-dynamic/Terraform.Provider.Scaffolding](https://github.com/pseudo-dynamic/Terraform.Provider.Scaffolding), but this requires an extension to `tfplugindocs` as it seems that the `go build` procedure is a fixed part of the `tfplugindocs generate` command.

So my question is, would you consider to add support for external Terraform plugin provider binaries by supporting specifiying a path pointing to the external Terraform plugin provider?

**Comment by teneko** [comment]
In case you give green light, I can provide a pull request.

My Idea would be to introduce a new argument called --provider-path and in case of specifying the argument, the `go build`-procedure gets omitted and the path is taken directly from the one specified by --provider-path. Honestly I just tested the command and looked in two or three source code files, so correct me if I am wrong.

**Comment by bflad** [comment]
Hi @teneko 👋 Thank you for raising this. In general, this seems like a reasonable request and proposed solution, however I have added this to our next team triage meeting to discuss further. We'll let you know afterwards. Thanks again!

**Comment by teneko** [comment]
And have you met once in the last 2 months? :smile:

**Comment by teneko** [comment]
Since it seems that this issue get ignored, please consider this issue as not planned.
