### ISSUE TITLE
Anchor links for nested blocks broken on registry docs

### ISSUE THREAD

**Issue by zippolyte** [hashicorp/terraform-plugin-docs#24]
When generating sections for documenting nested blocks, the generator creates a `<a id="nestedblock--something"></a>` just above the markdown title level 3 that is generated `### Nested schema for something` and generates links that point to the former anchor instead of the one generated by the markdown title.
Issue is the `id="nestedblock--something"` part of the HTML link is removed in the final docs on the registry (on the preview too), leaving only `<a></a>`, so the anchor links are effectively broken.

See for example this page https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor
Generated from https://github.com/DataDog/terraform-provider-datadog/blob/master/docs/resources/monitor.md
Using the `tfplugindocs` v0.3.1

Now the question is: should this be fixed in the registry site where the markdown files are rendered to HTML, so that the `id` attribute doesn't disappear, or should it be fixed in this generator so that it directly uses the id that the markdown titles will get after rendering.

Thanks for having a look !
And thanks for this docs generator !

Cheers

**Comment by zippolyte** [comment]
Hi, any news to share about this ?
Thanks

**Comment by paultyng** [comment]
I'm taking a look, I believe this used to work and it works in the GitHub preview so I think this is a registry issue we'll need to address. I'd prefer to the markdown to work as close to GitHub Flavored Markdown as is possible here.

**Comment by paultyng** [comment]
Just for context, the reason it doesn't use the automatically generated ID is that if you have multiple nesting levels, the titles are not necessarily unique, since Terraform doesn't have the concept of "named types". You could have a `something` nested section under multiple things that is different. Maybe that should be incorporated in to the titles though, I'm not sure.

**Comment by zippolyte** [comment]
Cool, thanks for the explanation !

**Comment by paultyng** [comment]
Ran this down internally, I think we recently switched our XSS library for the markdown renderer and erred on the side of it being a little too strict, so will be adding names/ids on anchors to the allow list hopefully later today.

**Comment by paultyng** [comment]
This is resolved in the registry UI now, will need to think a bit more about if we can just use the heading ID's instead though: https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#nestedblock--monitor_thresholds
