### ISSUE TITLE
Data source output markdown file missing example usage subsection

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform-plugin-docs#241]
Terraform 1.3.9
terraform-plugin-docs 0.14.1

The documentation, tutorial, and providers imply that if one has a data source `foo`, and places an example TF config at `examples/data-sources/foo/data-source.tf`, then during the TF plugin docs generation the output markdown file within `docs/data-sources/foo.md` will contain a subsection titled `Example Usage` with the contents of the aforementioned `data-source.tf` file. However, that does not occur by default. There is no such subsection or contents in the generated markdown file.

Am I misunderstanding the documentation? Do I need a `templates/data-sources/foo.md.tmpl` for every data source to ensure the `Example Usage` subsection is populated with the content?

All other aspects of the executable are behaving as expected including e.g. all other sections and subsections of the output markdown files, and the behavior of `templates/index.md.tmpl` regarding the content of `docs/index.md`.

**Comment by austinvalle** [comment]
Hi @mschuchard 👋🏻 , thanks for submitting the issue and sorry you're running into trouble here.

You're correct in your understanding that the example files should be automatically included without the usage of a `.tmpl` file. I believe our documentation is not explicit enough with the expected path of the example config.

The current README notes the expected path is `examples/data-sources/<data source name>/data-source.tf`, however, `<data source name>` is expected to include the prefix of the provider name.

So for your example, the expected path would be: `examples/data-sources/provider_foo/data-source.tf`, where `provider` is the value provided in the [Provider Metadata function](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/provider#MetadataResponse.TypeName).

Does that information help solve your issue? If so, I will update the documentation in the README to be more explicit about this path.

**Comment by mschuchard** [comment]
Thank you for the clarification. Prefixing the provider name to the path in the `<data_source_name>` did resolve the issue. I doublechecked the references I was using, and notice the provider was indeed prefixed to the path; so this is mostly my fault.

Thanks also to the link for the Sprig template for reference.

**Comment by austinvalle** [comment]
No worries! I opened a PR to add more clarifying info to our README 👍🏻
