### ISSUE TITLE
Hide specific config options in the docs

### ISSUE THREAD

**Issue by pgier** [hashicorp/terraform-plugin-docs#274]
My provider plugin has some config fields that are used during testing, but should basically never be used with the released versions of the plugin.  Is there a way to hide these specific fields in the generated documentation?

**Comment by bflad** [comment]
Since there has not been any additional comments, interest, or use cases described for this feature request, I'm going to close this issue. The above comment has some anticipated methodologies for handling this situation and a link to HashiCorp Discuss to ask further questions about those.
