### ISSUE TITLE
Resource schema documentation generation ignores property values

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform-plugin-docs#275]
For a given schema:

```go
"foo": resource.StringAttribute{
    Optional:    !boolSwitch,
    Computed:    boolSwitch,
    Description: "Cool beans.",
}
```

the property values of `Required`, `Optional`, and `Computed` are ignored during document generation. The observed behavior is that if the `Computed` field exists in the `struct` then the generated document for the schema will mark the parameter `foo` as `Read-Only` regardless of property values.

**Comment by bendbennett** [comment]
Hi @mschuchard 👋 

I've just tried to reproduce the behaviour you describe.

I'm seeing the following:

**Required**

```go
"configurable_attribute": schema.StringAttribute{
	Required:            true,
	MarkdownDescription: "Example configurable attribute",
},
```

```markdown
### Required

- `configurable_attribute` (String) Example attribute
```

**Optional**

```go
schema.StringAttribute{
	Optional:            true,
	MarkdownDescription: "Example attribute",
},
```

```markdown
### Optional

- `configurable_attribute` (String) Example attribute
```

**Optional + Computed**

```go
"configurable_attribute": schema.StringAttribute{
	Optional:            true,
	Computed:            true,
	MarkdownDescription: "Example attribute",
},
```

```markdown
### Optional

- `configurable_attribute` (String) Example attribute
```

**Computed**

```go
"configurable_attribute": schema.StringAttribute{
	Computed:            true,
	MarkdownDescription: "Example attribute",
},
```

```markdown
### Read-Only

- `configurable_attribute` (String) Example attribute
```

Specifying that an attribute is both _optional_ and _computed_ seems to mark the attribute as `Optional` in the docs at this end.

**Comment by mschuchard** [comment]
Yes I am returning here to note that now my `go generate` is producing the expected schema documentation. I think I had some bizarre fluke during one execution because that was the only time I noticed the behavior.
Closing.
