### ISSUE TITLE
Adding `CustomType` to a `ListAttribute` changes generated description to `List of Dynamic`

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-plugin-docs#342]
### Terraform CLI and terraform-plugin-docs Versions

```console
% tfplugindocs -v
tfplugindocs Version dev
```

In `go.mod`: `github.com/hashicorp/terraform-plugin-docs v0.18.0`

### Provider Code

```go
"health_check_arns": schema.ListAttribute{ /*START ATTRIBUTE*/
                        ElementType: types.StringType,
                        CustomType:  cctypes.MultisetType,
                        Description: "The Amazon Resource Names (ARNs) of the health check to associate with the protection.",
                        Optional:    true,
                        Computed:    true,
                        Validators: []validator.List{ /*START VALIDATORS*/
                                listvalidator.SizeAtMost(1),
                                listvalidator.ValueStringsAre(
                                        stringvalidator.LengthBetween(1, 2048),
                                ),
                        }, /*END VALIDATORS*/
                        PlanModifiers: []planmodifier.List{ /*START PLAN MODIFIERS*/
                                listplanmodifier.UseStateForUnknown(),
                        }, /*END PLAN MODIFIERS*/
                }, /*END ATTRIBUTE*/
```

### Expected Behavior

Generate:

`health_check_arns` (List of String) The Amazon Resource Names (ARNs) of the health check to associate with the protection.

### Actual Behavior

Generated:

`health_check_arns` (List of Dynamic) The Amazon Resource Names (ARNs) of the health check to associate with the protection.

### Steps to Reproduce

1. `tfplugindocs generate --flags`

### How much impact is this issue causing?

Medium

### Additional Information

Relates https://github.com/hashicorp/terraform-provider-awscc/pull/1463.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Drive-by note: The framework website documentation does not go into too many of the details about creating a custom collection type, but in that situation, the custom type "owns" the entire type definition (e.g. the _attribute_ `ElementType` is not effective). You can see some of that implementation at play here:

https://github.com/hashicorp/terraform-plugin-framework/blob/4ca111592bfec2bec39662261ad147002bc56c34/resource/schema/list_attribute.go#L199-L208

Maybe the framework could/should raise an attribute implementation error when it detects both `CustomType` and `ElementType` being set.

In your situation it might be a matter of doing something like (removing the exported `MultisetType` variable and instead exporting the type directly):

```go
CustomType:  cctypes.MultisetType{basetypes.ListType{ElementType: basetypes.StringType}},
```

That should cause the GetProviderSchema RPC to return the "full" type information.

**Comment by bflad** [comment]
For what its worth about:

> Maybe the framework could/should raise an attribute implementation error when it detects both CustomType and ElementType being set.

Could also be turned around as a framework feature request that attributes could automatically do what you tried to do there with both fields. There is the [`attr.TypeWithElementType` interface](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/attr#TypeWithElementType) that could potentially help in this situation if the `CustomType` implemented it. While it would likely solve this situation, I'm not sure off the top of my head whether just adjusting that `GetType()` logic would fully enable correct type handling everywhere else in the framework though. We would need to verify. 😄

**Comment by ewbankkit** [comment]
Yes, removing the `ElementType` (and reworking `MultisetType`) works. Thanks.
