### ISSUE TITLE
Go generate seems to be not picking up latest changes from the current project directory, somehow .git directory seems to overshadow the current project directory

### ISSUE THREAD

**Issue by kavinbalagen** [hashicorp/terraform-plugin-docs#345]
### Terraform CLI and terraform-plugin-docs Versions

Terraform v1.6.2

### Provider Code

```go
n/a
```

### Expected Behavior

the markdowns generated need to reflect the source from the current project directory 

### Actual Behavior

somehow old changes from .git directory seems to shadow current project directory's latest changes

### Steps to Reproduce

using tools.go method. so we use 'go generate'

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @kavinbalagen 👋 Thank you for raising this and sorry you ran into trouble here.

I think we will need some additional information about your setup to reproduce this sort of issue. If you can provide us with step-by-step reproduction instructions, we can take a deeper look.

As far as I am aware, this tool has no special awareness of Git nor the `.git` directory, so I would ensure that any staged changes are actually saved to disk as expected prior to calling this tool.

**Comment by bflad** [comment]
Hi again @kavinbalagen 👋 Since we haven't heard back from you, I'm going to close this issue for now, but if you can provide the additional information please reach out and we can take a fresh look.
