### ISSUE TITLE
`Migrate` appends a new copy of the file each time it is executed. 

### ISSUE THREAD

**Issue by sheneska** [hashicorp/terraform-plugin-docs#362]
### Terraform CLI and terraform-plugin-docs Versions

`github.com/hashicorp/terraform-plugin-docs v0.19.0`

### Provider Code

```go
N/A
```

### Expected Behavior

When `migrate` is executed it creates new templates from existing documentation.

### Actual Behavior

Each time the `migrate` command is executed, it appends a copy of the previous file to the existing template. 

### Steps to Reproduce

1. `tfplugindocs` migrate

### How much impact is this issue causing?

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @sheneska 👋 Thank you for raising this and sorry for the trouble here. I was able to reproduce this in our testing and this will be fixed in the next release. Thanks again for the report!
