### ISSUE TITLE
Terraform Plugin Protocol Version 6 / Providers Schema JSON Version 0.2 Support

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-docs#49]
## Description

As part of the upcoming Terraform CLI version 0.15 release, a newer version 6 of the Terraform Plugin Protocol is now available. This protocol bump includes goodies such as `NestedType` that will benefit the future of plugin development and documentation. The changes to the output of `terraform providers schema -json` are denoted with a bump in that format version from 0.1 to 0.2.

## References

- https://github.com/hashicorp/terraform/pull/27699
- https://github.com/hashicorp/terraform/pull/27826
- https://github.com/hashicorp/terraform/pull/28055
- https://github.com/hashicorp/terraform/pull/28115
- https://github.com/hashicorp/terraform-json/issues/27
- https://github.com/hashicorp/terraform-json/pull/28

**Comment by radeksimko** [comment]
FYI these PRs were merged
 - https://github.com/hashicorp/terraform-json/pull/28
 - https://github.com/hashicorp/terraform-json/pull/29
 - https://github.com/hashicorp/terraform-json/pull/30

and are now available as part of `0.9.0`.
