### ISSUE TITLE
Still being worked on?

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform-plugin-docs#69]
Hi, I'm just curious if `tfplugindocs` is still being worked on?

Just slightly worried to notice no commits for several months when quite active previously, except moving an Action from @paultyng's repo to Hashicorp's; that not authored or committed by him (instead @smacfarlane), who was previously the committer on almost all and authored most.

Thanks! 🤞🏻 it's nothing, just a priority shift 🙂

**Comment by displague** [comment]
I'm also interested in the state of this project. We began the work to adopt this generator and are getting ready to use it. We've run into some problems that have been reported here and on other projects adopting this generator. #28 , #66 , #65.

I understand that the original author is no longer associated with the org.
I hope to see more attention on this project now that it is in the official org!

**Comment by OJFord** [comment]
Thanks @paddycarver, no problem, that's what I hoped really (de-prioritised as opposed to dropped).
