### ISSUE TITLE
Preview rendered site

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform-plugin-docs#8]
Just a feature idea - I realise it'll at best be a 'nice-to-have', far more to be done first sort of thing - but I think it'd be really helpful for working on provider docs; making sure the flow makes sense and everything renders correctly, to be able to serve a local preview roughly as it will render on the registry.

i.e. something like:
```
$tfplugindocs serve
Serving myprovider docs on http://localhost:8123
```

(And just to say - even without that, I'm already extremely glad to find this generator, early days as it may be. Beats the copy-pasting-renaming between projects I have been doing. :blush: Great stuff!)

**Comment by paultyng** [comment]
Definitely would like to do this, its complicated by the fact that the registry is a SPA with some assumptions about runtime, but its on our roadmap. I'm going to merge this with #5  and add some additional details in there as its a similar ask.
